[package]
name = "codecov-sample"
version = "0.1.0"
authors = ["dimitri <dimitri.torfs@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
